# Generated by Django 5.2.14 on 2026-05-30 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0002_short_created_at_short_video_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='thumbnail',
            field=models.ImageField(max_length=500, upload_to='shorts/'),
        ),
    ]
