# Generated by Django 5.2.14 on 2026-05-30 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shorts', '0003_alter_short_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='short',
            name='thumbnail',
            field=models.ImageField(max_length=1000, upload_to='shorts/'),
        ),
    ]
